### ISSUE TITLE
Create new $textblack as #232323

### ISSUE THREAD

**Issue by chrisbalt** [MicrosoftDotCom/picchu#1]
`$textblack` = `$darkgrey` = `#232323`

**Comment by kylezinter** [comment]
just noticed this now @chrisbalt, what is this? all picchu text color is supposed to be set to this?

**Comment by TonyPeterson** [comment]
text value should be #2F2F2F... did you need #232323 for a specific use case?

**Comment by kylezinter** [comment]
This is already done, I used 2F2F2F.

Line 32 of colors.
