### ISSUE TITLE
'Full' grids add horizontal scrolling to page

### ISSUE THREAD

**Issue by jordanisip** [MicrosoftDotCom/picchu#2]
Adding `.full` to `.ms-grid` makes the page wider than 100% (adds horizontal scrolling). Can be seen on here: http://msdotcom.azurewebsites.net/Grid/ with full grid toggled.

**Comment by kylezinter** [comment]
Interesting, will definitely fix today as well. Looking into into now.

**Comment by jordanisip** [comment]
:+1: thanks

**Comment by kylezinter** [comment]
@jordanisip fixed now. please let me know if you still see this occurring anywhere.
