### ISSUE TITLE
Worth adding lighter gray shades?

### ISSUE THREAD

**Issue by jordanisip** [MicrosoftDotCom/picchu#3]
There doesn't seem to be a good way to use a very light grey color eg. #F5F5F5. Using utility background classes - `.lightgray-l3-bgc` is the lightest gray available. Not sure if it makes sense to add lighter shades.

**Comment by kylezinter** [comment]
@jordanisip we just last night updated the picchu colors to match the ms brand colors. there are a few more grays with shades and tints available. check it out on the demo site here and let me know if that doesn't cover you. http://msdotcom.azurewebsites.net/Color/

**Comment by jordanisip** [comment]
Great stuff, thanks!

**Comment by kylezinter** [comment]
@jordanisip Heyo, quick update after working with design on my side today. We had to update how we were doing the grays. This update has now been done, you can see the updates at the page again. We now just have gray utility classes and then one light gray exception. Let me know if that's not enough and causes you problems or you have any questions.

**Comment by jordanisip** [comment]
Cool, thanks for the heads up. We'll update Picchu on our end today and
make adjustments based on the changes.


--
Jordan Isip
Twitter: @fixie <http://twitter.com/fixie>
