### ISSUE TITLE
No white button available

### ISSUE THREAD

**Issue by jordanisip** [MicrosoftDotCom/picchu#4]
No `.white` button available. Needed on top of backgrounds with color. Example:

![l2iafo7pwwez](https://cloud.githubusercontent.com/assets/5899/6508894/99c3c208-c329-11e4-95f6-6d996e4a9871.png)

**Comment by kylezinter** [comment]
Adding this morning, thank you for pointing out.

**Comment by jordanisip** [comment]
No prob. Do we currently have a process for getting the latest Picchu lib into the proto repo?

**Comment by kylezinter** [comment]
@jordanisip fixed now. I haven't been owning that repo so not sure, you could just add it as a submodule and then pull updates as needed or could just pull the latest code and place it in.

**Comment by jordanisip** [comment]
Sounds good, thanks Kyle. 

Just pulled the latest. Not a huge deal since I can apply text color utility classes, but you may want to set the default color on a white button to be something other than white. Using `.white` class on button:

![37mvjkiq7u-f](https://cloud.githubusercontent.com/assets/5899/6516712/3f0458e4-c362-11e4-80ad-b2412cd20d52.png)
