### ISSUE TITLE
Manual Colspans Classnames Inconsistent?

### ISSUE THREAD

**Issue by shaekuronen** [MicrosoftDotCom/picchu#5]
`.l-col-4-24` and `.xl-col-4-24` set width to 16.66667%

What I'm not understanding is why `.xs-col-3-24` sets the width to 50%?

Seems like `.xs-col-12-24` should be 50%?

To get a grid layout that goes from 2 col mobile, to 3 col tablet, to 6 col desktop, I ended up using `.xs-col-3-24.s-col-4-24.m-col-8-24.l-col-8-24.xl-col-4-24` which seems a little off.

**Comment by kylezinter** [comment]
@shaekuronen  let's chat about this, this is due to how the columns breakdown. i'm very open to new ideas on how to handle this/name the classes.

**Comment by kylezinter** [comment]
Closing. Ending up decoupling the manual class names from the automatic grid breakdown.
